-- LINDA Config file for PMDG 737NGX
-- Generated by LINDA Configurator at 1703291328
-- using LINDA 2.9.4


-- ############################################### --
-- ## EFIS block mode1
-- ############################################### --

-- EFIS block buttons and switches
EFIS1 = {
["ENABLED"]		= true  ,
["IDENT"]		= "EFIS"  ,
["FPV ."] 		= NGX_EFIS_FPV  ,
["MTR ."] 		= NGX_EFIS_MTRS  ,
["WX  ."] 		= NGX_EFIS_WXR  ,
["STA ."] 		= NGX_EFIS_STA  ,
["WPT ."] 		= NGX_EFIS_WPT  ,
["ARPT."] 		= NGX_EFIS_ARPT  ,
["DATA."] 		= NGX_EFIS_DATA  ,
["POS ."] 		= NGX_EFIS_POS  ,
["TERR."] 		= NGX_EFIS_TERR  ,
["VORL:"] 		= NGX_EFIS_NAV1_adf  ,
["VORR:"] 		= NGX_EFIS_NAV2_adf  ,
["VORL."] 		= NGX_EFIS_NAV1_vor  ,
["VORR."] 		= NGX_EFIS_NAV2_vor  ,
}


-- EFIS MINS knob
MINS1 = {
["A SHOW"]		= empty  ,
["A  +"]		= NGX_EFIS_MINS_inc  ,
["A ++"]		= NGX_EFIS_MINS_inc  ,
["A  -"]		= NGX_EFIS_MINS_dec  ,
["A --"]		= NGX_EFIS_MINS_dec  ,
["PRESS"] 		= NGX_EFIS_MINS_RST  ,
["B SHOW"]		= empty  ,
["B  +"]		= empty  ,
["B ++"]		= empty  ,
["B  -"]		= empty  ,
["B --"]		= empty  ,
}


-- EFIS BARO knob
BARO1 = {
["A SHOW"]		= empty  ,
["A  +"]		= NGX_EFIS_BARO_inc  ,
["A ++"]		= NGX_EFIS_BARO_inc  ,
["A  -"]		= NGX_EFIS_BARO_dec  ,
["A --"]		= NGX_EFIS_BARO_dec  ,
["PRESS"] 		= NGX_EFIS_BARO_STD_toggle  ,
["B SHOW"]		= empty  ,
["B  +"]		= empty  ,
["B ++"]		= empty  ,
["B  -"]		= empty  ,
["B --"]		= empty  ,
}


-- EFIS CTR knob
CTR1 = {
["A SHOW"]		= empty  ,
["A  +"]		= NGX_EFIS_ND_MODE_inc  ,
["A ++"]		= NGX_EFIS_ND_MODE_inc  ,
["A  -"]		= NGX_EFIS_ND_MODE_dec  ,
["A --"]		= NGX_EFIS_ND_MODE_dec  ,
["PRESS"] 		= NGX_EFIS_ND_MODE_CTR  ,
["B SHOW"]		= empty  ,
["B  +"]		= empty  ,
["B ++"]		= empty  ,
["B  -"]		= empty  ,
["B --"]		= empty  ,
}


-- EFIS TFC knob
TFC1 = {
["A SHOW"]		= empty  ,
["A  +"]		= NGX_EFIS_ND_RNG_inc  ,
["A ++"]		= NGX_EFIS_ND_RNG_inc  ,
["A  -"]		= NGX_EFIS_ND_RNG_dec  ,
["A --"]		= NGX_EFIS_ND_RNG_dec  ,
["PRESS"] 		= NGX_EFIS_ND_RNG_TFC  ,
["B SHOW"]		= empty  ,
["B  +"]		= empty  ,
["B ++"]		= empty  ,
["B  -"]		= empty  ,
["B --"]		= empty  ,
}


-- ############################################### --
-- ## EFIS block mode2
-- ############################################### --

-- EFIS block buttons and switches
EFIS2 = {
["ENABLED"]		= true  ,
["IDENT"]		= "Sec"  ,
["FPV ."] 		= NGX_HGS_toggle  ,
["MTR ."] 		= NGX_HGS_mode  ,
["WX  ."] 		= WXR_L_TFR  ,
["STA ."] 		= WXR_L_WX  ,
["WPT ."] 		= WXR_L_WX_T  ,
["ARPT."] 		= WXR_L_MAP  ,
["DATA."] 		= WXR_L_GC  ,
["POS ."] 		= WXR_AUTO  ,
["TERR."] 		= WXR_TEST  ,
["VORL:"] 		= empty  ,
["VORR:"] 		= empty  ,
["VORL."] 		= empty  ,
["VORR."] 		= empty  ,
}


-- EFIS MINS knob
MINS2 = {
["A SHOW"]		= empty  ,
["A  +"]		= empty  ,
["A ++"]		= empty  ,
["A  -"]		= empty  ,
["A --"]		= empty  ,
["PRESS"] 		= empty  ,
["B SHOW"]		= empty  ,
["B  +"]		= empty  ,
["B ++"]		= empty  ,
["B  -"]		= empty  ,
["B --"]		= empty  ,
}


-- EFIS BARO knob
BARO2 = {
["A SHOW"]		= empty  ,
["A  +"]		= NGX_AUTOBRAKE_inc  ,
["A ++"]		= NGX_AUTOBRAKE_inc  ,
["A  -"]		= NGX_AUTOBRAKE_dec  ,
["A --"]		= NGX_AUTOBRAKE_dec  ,
["PRESS"] 		= NGX_AUTOBRAKE_OFF  ,
["B SHOW"]		= empty  ,
["B  +"]		= empty  ,
["B ++"]		= empty  ,
["B  -"]		= empty  ,
["B --"]		= empty  ,
}


-- EFIS CTR knob
CTR2 = {
["A SHOW"]		= empty  ,
["A  +"]		= WXR_L_TILT_CONTROL_inc  ,
["A ++"]		= WXR_L_TILT_CONTROL_inc  ,
["A  -"]		= WXR_L_TILT_CONTROL_dec  ,
["A --"]		= WXR_L_TILT_CONTROL_dec  ,
["PRESS"] 		= empty  ,
["B SHOW"]		= empty  ,
["B  +"]		= empty  ,
["B ++"]		= empty  ,
["B  -"]		= empty  ,
["B --"]		= empty  ,
}


-- EFIS TFC knob
TFC2 = {
["A SHOW"]		= empty  ,
["A  +"]		= WXR_L_GAIN_CONTROL_inc  ,
["A ++"]		= WXR_L_GAIN_CONTROL_inc  ,
["A  -"]		= WXR_L_GAIN_CONTROL_dec  ,
["A --"]		= WXR_L_GAIN_CONTROL_dec  ,
["PRESS"] 		= empty  ,
["B SHOW"]		= empty  ,
["B  +"]		= empty  ,
["B ++"]		= empty  ,
["B  -"]		= empty  ,
["B --"]		= empty  ,
}


-- ############################################### --
-- ## EFIS block mode3
-- ############################################### --

-- EFIS block buttons and switches
EFIS3 = {
["ENABLED"]		= true  ,
["IDENT"]		= "DUs"  ,
["FPV ."] 		= NGX_N1SET_MODE_auto  ,
["MTR ."] 		= NGX_SPDREF_MODE_auto  ,
["WX  ."] 		= NGX_MFD_SELECTOR_ENG  ,
["STA ."] 		= NGX_MFD_SELECTOR_SYS  ,
["WPT ."] 		= NGX_MFD_SELECTOR_CR  ,
["ARPT."] 		= NGX_HGS_toggle  ,
["DATA."] 		= NGX_HGS_mode  ,
["POS ."] 		= NGX_EFIS_MINS_MODE_toggle  ,
["TERR."] 		= NGX_EFIS_BARO_MODE_toggle  ,
["VORL:"] 		= NGX_AP_TEST_DISENGAGE_2  ,
["VORR:"] 		= NGX_LIGHTS_toggle  ,
["VORL."] 		= NGX_AP_TEST_DISENGAGE_1  ,
["VORR."] 		= NGX_LIGHTS_test  ,
}


-- EFIS MINS knob
MINS3 = {
["A SHOW"]		= empty  ,
["A  +"]		= NGX_DU1_MAIN_inc  ,
["A ++"]		= NGX_DU1_MAIN_inc  ,
["A  -"]		= NGX_DU1_MAIN_dec  ,
["A --"]		= NGX_DU1_MAIN_dec  ,
["PRESS"] 		= NGX_DU1_MAIN_norm  ,
["B SHOW"]		= empty  ,
["B  +"]		= empty  ,
["B ++"]		= empty  ,
["B  -"]		= empty  ,
["B --"]		= empty  ,
}


-- EFIS BARO knob
BARO3 = {
["A SHOW"]		= empty  ,
["A  +"]		= NGX_DU1_LOWER_inc  ,
["A ++"]		= NGX_DU1_LOWER_inc  ,
["A  -"]		= NGX_DU1_LOWER_dec  ,
["A --"]		= NGX_DU1_LOWER_dec  ,
["PRESS"] 		= NGX_DU1_LOWER_NORM  ,
["B SHOW"]		= empty  ,
["B  +"]		= empty  ,
["B ++"]		= empty  ,
["B  -"]		= empty  ,
["B --"]		= empty  ,
}


-- EFIS CTR knob
CTR3 = {
["A SHOW"]		= empty  ,
["A  +"]		= NGX_N1SET_inc  ,
["A ++"]		= NGX_N1SET_inc  ,
["A  -"]		= NGX_N1SET_dec  ,
["A --"]		= NGX_N1SET_dec  ,
["PRESS"] 		= NGX_N1SET_MODE_cycle  ,
["B SHOW"]		= empty  ,
["B  +"]		= empty  ,
["B ++"]		= empty  ,
["B  -"]		= empty  ,
["B --"]		= empty  ,
}


-- EFIS TFC knob
TFC3 = {
["A SHOW"]		= empty  ,
["A  +"]		= NGX_SPDREF_inc  ,
["A ++"]		= NGX_SPDREF_inc  ,
["A  -"]		= NGX_SPDREF_dec  ,
["A --"]		= NGX_SPDREF_dec  ,
["PRESS"] 		= NGX_SPDREF_MODE_cycle  ,
["B SHOW"]		= empty  ,
["B  +"]		= empty  ,
["B ++"]		= empty  ,
["B  -"]		= empty  ,
["B --"]		= empty  ,
}


-- ############################################### --
-- ## MCP block mode1
-- ############################################### --

-- MCP block buttons and switches
MCP1 = {
["ENABLED"]	= true  ,
["IDENT"] 	= "std"  ,
["TO  ."] 	= NGX_AP_TOGA  ,
["GA  ."] 	= NGX_AP_P_reset  ,
["N1  ."] 	= NGX_AP_N1  ,
["SPD ."] 	= NGX_AP_SPEED  ,
["FLCH."] 	= NGX_AP_LVLCHG  ,
["SEL ."] 	= NGX_AP_SPD_INTV  ,
["HHLD."] 	= NGX_AP_HDGSEL  ,
["AHLD."] 	= NGX_AP_ALTHLD  ,
["VHLD."] 	= NGX_AP_VS  ,
["APP ."] 	= NGX_AP_APP  ,
["VNAV."] 	= NGX_AP_VNAV  ,
["LNAV."] 	= NGX_AP_LNAV  ,
["CMDA."] 	= NGX_AP_CMDA_toggle  ,
["CMDB."] 	= NGX_AP_CMDB_toggle  ,
["CMDC."] 	= NGX_WARN_ALL_reset  ,
["LOC ."] 	= NGX_AP_VORLOC  ,
["CWSA."] 	= NGX_AP_CWSA  ,
["CWSB."] 	= NGX_AP_CWSB  ,
["AT  ."] 	= NGX_AP_ATHR_arm  ,
["AT  :"] 	= NGX_AP_ATHR_off  ,
["FD  ."] 	= NGX_AP_FD_both_on  ,
["FD  :"] 	= NGX_AP_FD_both_off  ,
["AP  ."]	= NGX_AP_MASTER_on  ,
["AP  :"] 	= NGX_AP_MASTER_off  ,
}


-- MCP SPD knob
SPD1 = {
["A SHOW"]	= empty  ,
["A  +"]	= NGX_AP_SPD_inc  ,
["A ++"]	= NGX_AP_SPD_incfast  ,
["A  -"]	= NGX_AP_SPD_dec  ,
["A --"]	= NGX_AP_SPD_decfast  ,
["PRESS"] 	= NGX_AP_SPD_INTV  ,
}


-- MCP HDG knob
HDG1 = {
["A SHOW"]	= empty  ,
["A  +"]	= NGX_AP_HDG_inc  ,
["A ++"]	= NGX_AP_HDG_incfast  ,
["A  -"]	= NGX_AP_HDG_dec  ,
["A --"]	= NGX_AP_HDG_decfast  ,
["PRESS"] 	= NGX_AP_HDG_BANK_toggle  ,
}


-- MCP ALT knob
ALT1 = {
["A SHOW"]	= empty  ,
["A  +"]	= NGX_AP_ALT_inc  ,
["A ++"]	= NGX_AP_ALT_incfast  ,
["A  -"]	= NGX_AP_ALT_dec  ,
["A --"]	= NGX_AP_ALT_decfast  ,
["PRESS"] 	= NGX_AP_ALT_INTV  ,
}


-- MCP VVS knob
VVS1 = {
["A SHOW"]	= empty  ,
["A  +"]	= NGX_AP_VS_inc  ,
["A ++"]	= NGX_AP_VS_inc  ,
["A  -"]	= NGX_AP_VS_dec  ,
["A --"]	= NGX_AP_VS_dec  ,
["PRESS"] 	= empty  ,
}


-- ############################################### --
-- ## MCP block mode2
-- ############################################### --

-- MCP block buttons and switches
MCP2 = {
["ENABLED"]	= true  ,
["IDENT"] 	= "CRS"  ,
["TO  ."] 	= empty  ,
["GA  ."] 	= empty  ,
["N1  ."] 	= empty  ,
["SPD ."] 	= empty  ,
["FLCH."] 	= empty  ,
["SEL ."] 	= empty  ,
["HHLD."] 	= empty  ,
["AHLD."] 	= empty  ,
["VHLD."] 	= empty  ,
["APP ."] 	= empty  ,
["VNAV."] 	= empty  ,
["LNAV."] 	= empty  ,
["CMDA."] 	= empty  ,
["CMDB."] 	= empty  ,
["CMDC."] 	= empty  ,
["LOC ."] 	= empty  ,
["CWSA."] 	= empty  ,
["CWSB."] 	= empty  ,
["AT  ."] 	= empty  ,
["AT  :"] 	= empty  ,
["FD  ."] 	= empty  ,
["FD  :"] 	= empty  ,
["AP  ."]	= empty  ,
["AP  :"] 	= empty  ,
}


-- MCP SPD knob
SPD2 = {
["A SHOW"]	= empty  ,
["A  +"]	= NGX_LandALT_inc  ,
["A ++"]	= NGX_LandALT_incfast  ,
["A  -"]	= NGX_LandALT_dec  ,
["A --"]	= NGX_LandALT_decfast  ,
["PRESS"] 	= empty  ,
}


-- MCP HDG knob
HDG2 = {
["A SHOW"]	= empty  ,
["A  +"]	= NGX_AP_BANK_inc  ,
["A ++"]	= NGX_AP_BANK_inc  ,
["A  -"]	= NGX_AP_BANK_dec  ,
["A --"]	= NGX_AP_BANK_dec  ,
["PRESS"] 	= NGX_AP_BANK_show  ,
}


-- MCP ALT knob
ALT2 = {
["A SHOW"]	= empty  ,
["A  +"]	= NGX_FLTALT_inc  ,
["A ++"]	= NGX_FLTALT_incfast  ,
["A  -"]	= NGX_FLTALT_dec  ,
["A --"]	= NGX_FLTALT_decfast  ,
["PRESS"] 	= empty  ,
}


-- MCP VVS knob
VVS2 = {
["A SHOW"]	= empty  ,
["A  +"]	= NGX_AP_CRS_LR_inc  ,
["A ++"]	= NGX_AP_CRS_LR_incfast  ,
["A  -"]	= NGX_AP_CRS_LR_dec  ,
["A --"]	= NGX_AP_CRS_LR_decfast  ,
["PRESS"] 	= NGX_AP_CRS_LR_toggle  ,
}


-- ############################################### --
-- ## MCP block mode3
-- ############################################### --

-- MCP block buttons and switches
MCP3 = {
["ENABLED"]	= true  ,
["IDENT"] 	= "Disp"  ,
["TO  ."] 	= empty  ,
["GA  ."] 	= empty  ,
["N1  ."] 	= empty  ,
["SPD ."] 	= empty  ,
["FLCH."] 	= empty  ,
["SEL ."] 	= empty  ,
["HHLD."] 	= empty  ,
["AHLD."] 	= empty  ,
["VHLD."] 	= NGX_LIGHTS_cycle  ,
["APP ."] 	= empty  ,
["VNAV."] 	= empty  ,
["LNAV."] 	= empty  ,
["CMDA."] 	= empty  ,
["CMDB."] 	= empty  ,
["CMDC."] 	= empty  ,
["LOC ."] 	= empty  ,
["CWSA."] 	= empty  ,
["CWSB."] 	= empty  ,
["AT  ."] 	= empty  ,
["AT  :"] 	= empty  ,
["FD  ."] 	= empty  ,
["FD  :"] 	= empty  ,
["AP  ."]	= empty  ,
["AP  :"] 	= empty  ,
}


-- MCP SPD knob
SPD3 = {
["A SHOW"]	= empty  ,
["A  +"]	= NGX_LIGHT_ALL_inc  ,
["A ++"]	= NGX_LIGHT_ALL_incfast  ,
["A  -"]	= NGX_LIGHT_ALL_dec  ,
["A --"]	= NGX_LIGHT_ALL_decfast  ,
["PRESS"] 	= NGX_LIGHT_ALL_show  ,
}


-- MCP HDG knob
HDG3 = {
["A SHOW"]	= empty  ,
["A  +"]	= NGX_FLOOD_ALL_inc  ,
["A ++"]	= NGX_FLOOD_ALL_incfast  ,
["A  -"]	= NGX_FLOOD_ALL_dec  ,
["A --"]	= NGX_FLOOD_ALL_decfast  ,
["PRESS"] 	= NGX_LIGHT_ALL_show  ,
}


-- MCP ALT knob
ALT3 = {
["A SHOW"]	= empty  ,
["A  +"]	= NGX_DU_ALL_BRT_inc  ,
["A ++"]	= NGX_DU_ALL_BRT_incfast  ,
["A  -"]	= NGX_DU_ALL_BRT_dec  ,
["A --"]	= NGX_DU_ALL_BRT_decfast  ,
["PRESS"] 	= NGX_DU_ALL_BRT_show  ,
}


-- MCP VVS knob
VVS3 = {
["A SHOW"]	= empty  ,
["A  +"]	= NGX_AP_CRSR_inc  ,
["A ++"]	= NGX_AP_CRSR_incfast  ,
["A  -"]	= NGX_AP_CRSR_dec  ,
["A --"]	= NGX_AP_CRSR_decfast  ,
["PRESS"] 	= NGX_LIGHTS_cycle  ,
}


-- ############################################### --
-- ## USER block mode1
-- ############################################### --

-- USER block buttons and switches
USER1 = {
["ENABLED"]	= true  ,
["IDENT"]	= "MOD1"  ,
["BTN1."] 	= NGX_AUTOBRAKE_dec  ,
["BTN2."] 	= NGX_AUTOBRAKE_inc  ,
["BTN3."] 	= NGX_XPND_MODE_dec  ,
["BTN4."] 	= NGX_XPND_MODE_inc  ,
["BTN5."] 	= NGX_TCAS_test  ,
["BTN6."] 	= VRI_EFIS_MODE_toggle  ,
["BTN7."] 	= VRI_MCP_MODE_toggle  ,
["BTN8."] 	= VRI_USER_MODE_toggle  ,
["LAMP."]   	= NGX_LIGHTS_PANEL_ALL_toggle  ,
}

-- ############################################### --
-- ## USER block mode2
-- ############################################### --

-- USER block buttons and switches
USER2 = {
["ENABLED"]	= true  ,
["IDENT"]	= "IVAO"  ,
["BTN1."] 	= IVAO_ShowHide_toggle  ,
["BTN2."] 	= IVAO_TCAS_toggle  ,
["BTN3."] 	= IVAO_XPDR_toggle  ,
["BTN4."] 	= IVAO_XPDR_toggle  ,
["BTN5."] 	= IVAO_Squawk_toggle  ,
["BTN6."] 	= VRI_EFIS_MODE_toggle  ,
["BTN7."] 	= VRI_MCP_MODE_toggle  ,
["BTN8."] 	= VRI_USER_MODE_toggle  ,
["LAMP."]   	= empty  ,
}

-- ############################################### --
-- ## USER block mode3
-- ############################################### --

-- USER block buttons and switches
USER3 = {
["ENABLED"]	= true  ,
["IDENT"]	= "Lght"  ,
["BTN1."] 	= NGX_LAND_ALL_toggle  ,
["BTN2."] 	= NGX_TAXI_ALL_toggle  ,
["BTN3."] 	= NGX_NAV_cycle  ,
["BTN4."] 	= NGX_BEACON_toggle  ,
["BTN5."] 	= NGX_DOME_toggle  ,
["BTN6."] 	= VRI_EFIS_MODE_toggle  ,
["BTN7."] 	= VRI_MCP_MODE_toggle  ,
["BTN8."] 	= VRI_USER_MODE_toggle  ,
["LAMP."]   	= empty  ,
}

-- ############################################### --
-- ## RADIOS block mode1
-- ############################################### --

-- RADIOS block buttons and switches
RADIOS = {
["COM ."]	= Default_COM_select  ,
["NAV ."]	= Default_NAV_select  ,
["ADF ."]	= Default_ADF_select  ,
["DME ."]	= Default_DME_select  ,
["TRAN."]	= Default_XPND_select  ,
["TFR ."]	= Default_RADIOS_swap  ,
["STBY."]	= Default_RADIOS_mode  ,

["COM1 Select"]	= empty  ,
["COM2 Select"]	= empty  ,
["COM1 Swap"]	= empty  ,
["COM2 Swap"]	= empty  ,
["COMs Mode"]	= Radios_COM_AUDIO_toggle  ,

["NAV1 Select"]	= empty  ,
["NAV2 Select"]	= empty  ,
["NAV1 Swap"]	= empty  ,
["NAV2 Swap"]	= empty  ,
["NAVs Mode"]	= Radios_NAV_AUDIO_toggle  ,

["ADF1 Select"]	= empty  ,
["ADF2 Select"]	= empty  ,
["ADFs Mode"]	= Radios_ADF_AUDIO_toggle  ,

["DME1 Select"]	= NGX_AP_CRS_LR_sync  ,
["DME2 Select"]	= NGX_AP_CRS_LR_sync  ,
["DMEs Mode"]	= Radios_DME_AUDIO_toggle  ,

["XPND Select"]	= empty  ,
["XPND Swap"]	= empty  ,
["XPND Mode"]	= Transponder_MODE_toggle  ,
}

DME1 = {
["A  +"]   	= NGX_AP_CRS_LR_inc  ,
["A ++"]   	= NGX_AP_CRS_LR_incfast  ,
["A  -"]   	= NGX_AP_CRS_LR_dec  ,
["A --"]   	= NGX_AP_CRS_LR_decfast  ,
["PRESS"]  	= NGX_AP_CRS_LR_toggle  ,
}

FRE1 = {
["A  +"]   	= Default_RADIOS_plus  ,
["A ++"]   	= Default_RADIOS_plusfast  ,
["A  -"]   	= Default_RADIOS_minus  ,
["A --"]   	= Default_RADIOS_minusfast  ,
["PRESS"]  	= Default_RADIOS_press  ,
}
